version: "3.5"
services:
  angular-app:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    container_name: angular-app
    ports:
      - "4200:4200"
    volumes:
      - ./ui:/angular-app
    environment:
      - STYLE=css
